---
# Source: showks-aggregator/templates/rolebinding.yml
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: showks-aggregator-access
  namespace: showks
rules:
- apiGroups: ["","apps","extensions"]
  resources: ["services","deployments","ingresses"]
  verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: showks-aggregator-access-binding
  namespace: showks
subjects:
  - kind: ServiceAccount
    name: default
roleRef:
  kind: Role
  name: showks-aggregator-access
  apiGroup: rbac.authorization.k8s.io

---
# Source: showks-aggregator/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: showks-aggregator-temp
  namespace: showks
  labels:
    app: showks-aggregator
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: app-port
  selector:
    app: showks-aggregator

---
# Source: showks-aggregator/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: showks-aggregator-temp
  namespace: showks
  labels:
    app: showks-aggregator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: showks-aggregator
  template:
    metadata:
      labels:
        app: showks-aggregator
    spec:
      containers:
        - name: showks-aggregator
          image: gcr.io/ipc-containerdays/showks-aggregator:stg-5a03ac983d9a96810e325d069757af583565e943
          ports:
            - name: app-port
              containerPort: 8081
              protocol: TCP

---
# Source: showks-aggregator/templates/ingress.yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: showks-aggregator-temp
  namespace: showks
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: aggregator.stg.showks.containerdays.jp
    http:
      paths:
      - path: /
        backend:
          serviceName: showks-aggregator-temp
          servicePort: 8081
  - host: aggregator.prod.showks.containerdays.jp
    http:
      paths:
      - path: /
        backend:
          serviceName: showks-aggregator-temp
          servicePort: 8081

