---
# Source: showks-form/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: showks-form-temp
  namespace: showks-system
  labels:
    app: showks-form-temp
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: app-port
  selector:
    app: showks-form-temp

---
# Source: showks-form/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: showks-form-temp
  labels:
    app: showks-form-temp
  namespace: showks-system
spec:
  replicas: 6
  selector:
    matchLabels:
      app: showks-form-temp
  template:
    metadata:
      labels:
        app: showks-form-temp
    spec:
      containers:
      - name: showks-form-temp
        image: cloudnativedaysjp/showks-form:stg-ba92788c0abef9b5c010bf480c3821203f093f67
        env:
          - name: RAILS_ENV
            value: "production"
          - name: RAILS_SERVE_STATIC_FILES
            value: "true"
          - name: RAILS_MASTER_KEY
            valueFrom:
              secretKeyRef:
                name: masterkey
                key: masterkey
          - name: RAILS_LOG_TO_STDOUT
            value: "true"
        ports:
        - containerPort: 3000


