---
# Source: showks-portal-frontend/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: showks-portal-frontend-temp
  namespace: showks
  labels:
    app: showks-portal-frontend
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: app-port
  selector:
    app: showks-portal-frontend

---
# Source: showks-portal-frontend/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: showks-portal-frontend-temp
  namespace: showks
  labels:
    app: showks-portal-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: showks-portal-frontend
  template:
    metadata:
      labels:
        app: showks-portal-frontend
    spec:
      containers:
        - name: showks-portal-frontend
          image: containerdaysjp/showks-portal-frontend:stg-4de9b8188f04dcadc9de793aac59ed5663f520f2
          ports:
            - name: app-port
              containerPort: 3000
              protocol: TCP

---
# Source: showks-portal-frontend/templates/ingress.yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: showks-portal-frontend-temp
  namespace: showks
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: portal.stg.showks.containerdays.jp
    http:
      paths:
      - path: /
        backend:
          serviceName: showks-portal-frontend-temp
          servicePort: 3000
  - host: portal.prod.showks.containerdays.jp
    http:
      paths:
      - path: /
        backend:
          serviceName: showks-portal-frontend-temp
          servicePort: 3000

