apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: weave-scope
  namespace: weave
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: scope.stg.showks.containerdays.jp
    http:
      paths:
      - path: /
        backend:
          serviceName: weave-scope-app
          servicePort: 80
